steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '$_REPOSITORY_URL/luca-ledger-webapp-$_ENVIRONMENT',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '$_REPOSITORY_URL/luca-ledger-webapp-$_ENVIRONMENT',
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_NAME',
        '--image',
        '$_REPOSITORY_URL/luca-ledger-webapp-$_ENVIRONMENT',
        '--region',
        '$_REGION',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

images:
  - '$_REPOSITORY_URL/luca-ledger-webapp-$_ENVIRONMENT'

substitutions:
  _ENVIRONMENT: ''
  _REPOSITORY_URL: ''
  _SERVICE_NAME: ''
  _REGION: ''

options:
  logging: CLOUD_LOGGING_ONLY
