name: Tag and Release on Push

permissions:
  contents: write
  actions: read

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Read Version from package.json
        id: get_version
        shell: bash
        run: |
          version=$(node -p 'require("./package.json").version')
          echo "Version from package.json: v$version"
          echo "version=v$version" >> $GITHUB_OUTPUT

      - name: Configure Git
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create and Push Tag
        id: create_tag
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version_tag="${{ steps.get_version.outputs.version }}"
          if git rev-parse "$version_tag" >/dev/null 2>&1; then
            echo "Tag $version_tag already exists. Exiting gracefully."
            echo "skipped=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          git tag "$version_tag"
          git push origin "$version_tag"
          echo "skipped=false" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: steps.create_tag.outputs.skipped != 'true'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: Automated release for version ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
